import { describe, expect, it, vi } from 'vitest';
import type { PrismaClient } from '@regimex/database';import type { BrokerOpenPosition } from '@regimex/shared';import type { Logger } from 'pino';
import { applyDemoGoldProfitTargets } from './goldProfitTargetReconcile.js';
function fixture(){
 const broker={brokerPositionId:'gold-42',symbol:'XAUUSD',direction:'SELL',status:'OPEN',volume:.01,entryPrice:100,stopLoss:110,takeProfit:80,floatingPnl:10} as BrokerOpenPosition;
 const local={id:'p42',symbol:'XAUUSD',interval:'15m',strategyId:'xau-trend-pullback-v1',origin:'ENGINE',metadata:{executionModel:'broker_demo_mt5'},status:'OPEN',direction:'SELL',volume:.01,entryPrice:100,initialStopLoss:110,stopLoss:110,takeProfit:80,currentPrice:90,brokerPositionId:broker.brokerPositionId};
 const event=vi.fn().mockResolvedValue({});
 const adapter={getStatus:vi.fn(()=>({isDemo:true,currency:'USD'})),getQuote:vi.fn(async()=>({symbol:'XAUUSD',bid:89.8,ask:90,mid:89.9,timestamp:Date.now()})),getPosition:vi.fn(async()=>({...broker})),closePosition:vi.fn(async()=>({brokerPositionId:broker.brokerPositionId,closePrice:90.2,realizedPnl:9.8,closedAt:Date.now(),closeReason:'TAKE_PROFIT' as const,appliedSpreadBps:0,appliedSlippageBps:0}))};
 const input={executionMode:'broker_demo_mt5',targetUsd:10 as number|undefined,prisma:{positionEvent:{create:event}} as unknown as PrismaClient,logger:{info:vi.fn(),warn:vi.fn()} as unknown as Logger,adapter,brokerOpen:[broker],localOpen:[local]};return {broker,local,adapter,event,input};
}
describe('Gold DEMO dollar exit',()=>{
 it('closes a full ticket at threshold, preserves stops/targets and defers DB closure to history',async()=>{const f=fixture();await applyDemoGoldProfitTargets(f.input);expect(f.adapter.closePosition).toHaveBeenCalledWith({brokerPositionId:'gold-42',reason:'TAKE_PROFIT',quote:expect.any(Object)});expect(f.input.brokerOpen).toEqual([]);expect(f.local.status).toBe('OPEN');expect(f.local.stopLoss).toBe(110);expect(f.broker.takeProfit).toBe(80);expect(f.event).toHaveBeenCalledWith({data:expect.objectContaining({eventType:'PROFIT_TARGET_CLOSE_CONFIRMED',payload:expect.objectContaining({targetUsd:10,triggerFloatingPnl:10,realizedPnl:9.8})})});});
 it('supports BUY with broker profit',async()=>{const f=fixture();f.local.direction='BUY';f.adapter.getPosition.mockResolvedValue({...f.broker,direction:'BUY',floatingPnl:12});await applyDemoGoldProfitTargets(f.input);expect(f.adapter.closePosition).toHaveBeenCalledTimes(1);});
 it.each(['broker_real_mt5','paper','broker_demo'])('excludes mode %s',async mode=>{const f=fixture();f.input.executionMode=mode;await applyDemoGoldProfitTargets(f.input);expect(f.adapter.getQuote).not.toHaveBeenCalled();});
 it.each([{isDemo:false,currency:'USD'},{isDemo:true,currency:'EUR'},{isDemo:true,currency:''}])('requires USD DEMO %j',async status=>{const f=fixture();f.adapter.getStatus.mockReturnValue(status);await applyDemoGoldProfitTargets(f.input);expect(f.adapter.getPosition).not.toHaveBeenCalled();});
 it.each([undefined,0,-10,NaN,Infinity])('invalid/off target %s',async target=>{const f=fixture();f.input.targetUsd=target;await applyDemoGoldProfitTargets(f.input);expect(f.adapter.closePosition).not.toHaveBeenCalled();});
 it.each([{symbol:'R_10'},{interval:'1m'},{strategyId:'other'},{origin:'MANUAL'},{status:'PENDING'},{metadata:{executionModel:'broker_real_mt5'}},{metadata:{executionModel:'broker_demo_mt5',ownedByRegimeX:false}}])('excludes scope %j',async patch=>{const f=fixture();Object.assign(f.local,patch);await applyDemoGoldProfitTargets(f.input);expect(f.adapter.closePosition).not.toHaveBeenCalled();});
 it.each([9.99,0,-10,NaN,Infinity])('rejects low/invalid profit %s',async profit=>{const f=fixture();f.broker.floatingPnl=profit;await applyDemoGoldProfitTargets(f.input);expect(f.adapter.closePosition).not.toHaveBeenCalled();});
 it('uses fresh rather than list profit',async()=>{const f=fixture();f.adapter.getPosition.mockResolvedValue({...f.broker,floatingPnl:9});await applyDemoGoldProfitTargets(f.input);expect(f.adapter.closePosition).not.toHaveBeenCalled();});
 it.each([{symbol:'R_10'},{direction:'BUY'},{status:'CLOSED'},{volume:.02},{brokerPositionId:'other'}])('rejects fresh mismatch %j',async patch=>{const f=fixture();f.adapter.getPosition.mockResolvedValue({...f.broker,...patch} as BrokerOpenPosition);await applyDemoGoldProfitTargets(f.input);expect(f.adapter.closePosition).not.toHaveBeenCalled();});
 it('ignores disappeared positions',async()=>{const f=fixture();f.adapter.getPosition.mockResolvedValue(null as unknown as BrokerOpenPosition);await applyDemoGoldProfitTargets(f.input);expect(f.adapter.closePosition).not.toHaveBeenCalled();});
 it.each([{timestamp:Date.now()-20000},{timestamp:Date.now()+20000},{bid:NaN},{ask:80},{symbol:'R_10'}])('rejects invalid quotes %j',async patch=>{const f=fixture();f.adapter.getQuote.mockResolvedValue({...await f.adapter.getQuote(),...patch});await applyDemoGoldProfitTargets(f.input);expect(f.adapter.closePosition).not.toHaveBeenCalled();});
 it('does not confirm failure; rechecks broker before retry',async()=>{const f=fixture();f.adapter.closePosition.mockRejectedValueOnce(Error('timeout'));await applyDemoGoldProfitTargets(f.input);expect(f.event).not.toHaveBeenCalled();expect(f.input.brokerOpen).toHaveLength(1);await applyDemoGoldProfitTargets(f.input);expect(f.adapter.getPosition).toHaveBeenCalledTimes(2);expect(f.event).toHaveBeenCalledTimes(1);});
 it('rejects bad close acknowledgement',async()=>{const f=fixture();f.adapter.closePosition.mockResolvedValue({...await f.adapter.closePosition(),brokerPositionId:'other'});f.adapter.closePosition.mockClear();await applyDemoGoldProfitTargets(f.input);expect(f.event).not.toHaveBeenCalled();expect(f.input.brokerOpen).toHaveLength(1);});
 it('serializes concurrent sessions',async()=>{const f=fixture();let release!:()=>void;const reply=await f.adapter.closePosition();f.adapter.closePosition.mockClear();f.adapter.closePosition.mockImplementation(async()=>{await new Promise<void>(r=>release=r);return reply;});const first=applyDemoGoldProfitTargets(f.input);await vi.waitFor(()=>expect(f.adapter.closePosition).toHaveBeenCalledTimes(1));await applyDemoGoldProfitTargets({...f.input,brokerOpen:[{...f.broker}]});release();await first;expect(f.adapter.closePosition).toHaveBeenCalledTimes(1);});
});
