/**
 * Official ProtoOA payload type IDs from Spotware cTrader Open API docs.
 * https://help.ctrader.com/open-api/model-messages/#protooaPayloadType
 */
export const ProtoOAPayloadType = {
  PROTO_OA_APPLICATION_AUTH_REQ: 2100,
  PROTO_OA_APPLICATION_AUTH_RES: 2101,
  PROTO_OA_ACCOUNT_AUTH_REQ: 2102,
  PROTO_OA_ACCOUNT_AUTH_RES: 2103,
  PROTO_OA_VERSION_REQ: 2104,
  PROTO_OA_VERSION_RES: 2105,
  PROTO_OA_NEW_ORDER_REQ: 2106,
  PROTO_OA_TRAILING_SL_CHANGED_EVENT: 2107,
  PROTO_OA_CANCEL_ORDER_REQ: 2108,
  PROTO_OA_AMEND_ORDER_REQ: 2109,
  PROTO_OA_AMEND_POSITION_SLTP_REQ: 2110,
  PROTO_OA_CLOSE_POSITION_REQ: 2111,
  PROTO_OA_ASSET_LIST_REQ: 2112,
  PROTO_OA_ASSET_LIST_RES: 2113,
  PROTO_OA_SYMBOLS_LIST_REQ: 2114,
  PROTO_OA_SYMBOLS_LIST_RES: 2115,
  PROTO_OA_SYMBOL_BY_ID_REQ: 2116,
  PROTO_OA_SYMBOL_BY_ID_RES: 2117,
  PROTO_OA_SYMBOLS_FOR_CONVERSION_REQ: 2118,
  PROTO_OA_SYMBOLS_FOR_CONVERSION_RES: 2119,
  PROTO_OA_SYMBOL_CHANGED_EVENT: 2120,
  PROTO_OA_TRADER_REQ: 2121,
  PROTO_OA_TRADER_RES: 2122,
  PROTO_OA_TRADER_UPDATE_EVENT: 2123,
  PROTO_OA_RECONCILE_REQ: 2124,
  PROTO_OA_RECONCILE_RES: 2125,
  PROTO_OA_EXECUTION_EVENT: 2126,
  PROTO_OA_SUBSCRIBE_SPOTS_REQ: 2127,
  PROTO_OA_SUBSCRIBE_SPOTS_RES: 2128,
  PROTO_OA_UNSUBSCRIBE_SPOTS_REQ: 2129,
  PROTO_OA_UNSUBSCRIBE_SPOTS_RES: 2130,
  PROTO_OA_SPOT_EVENT: 2131,
  PROTO_OA_ORDER_ERROR_EVENT: 2132,
  PROTO_OA_DEAL_LIST_REQ: 2133,
  PROTO_OA_DEAL_LIST_RES: 2134,
  PROTO_OA_SUBSCRIBE_LIVE_TRENDBAR_REQ: 2135,
  PROTO_OA_UNSUBSCRIBE_LIVE_TRENDBAR_REQ: 2136,
  PROTO_OA_GET_TRENDBARS_REQ: 2137,
  PROTO_OA_GET_TRENDBARS_RES: 2138,
  PROTO_OA_EXPECTED_MARGIN_REQ: 2139,
  PROTO_OA_EXPECTED_MARGIN_RES: 2140,
  PROTO_OA_MARGIN_CHANGED_EVENT: 2141,
  PROTO_OA_ERROR_RES: 2142,
  PROTO_OA_CASH_FLOW_HISTORY_LIST_REQ: 2143,
  PROTO_OA_CASH_FLOW_HISTORY_LIST_RES: 2144,
  PROTO_OA_GET_TICKDATA_REQ: 2145,
  PROTO_OA_GET_TICKDATA_RES: 2146,
  PROTO_OA_ACCOUNTS_TOKEN_INVALIDATED_EVENT: 2147,
  PROTO_OA_CLIENT_DISCONNECT_EVENT: 2148,
  PROTO_OA_GET_ACCOUNTS_BY_ACCESS_TOKEN_REQ: 2149,
  PROTO_OA_GET_ACCOUNTS_BY_ACCESS_TOKEN_RES: 2150,
  PROTO_OA_GET_CTID_PROFILE_BY_TOKEN_REQ: 2151,
  PROTO_OA_GET_CTID_PROFILE_BY_TOKEN_RES: 2152,
  PROTO_OA_SYMBOL_CATEGORY_REQ: 2153,
  PROTO_OA_SYMBOL_CATEGORY_RES: 2154,
  PROTO_OA_DEPTH_EVENT: 2155,
  PROTO_OA_SUBSCRIBE_DEPTH_QUOTES_REQ: 2156,
  PROTO_OA_SUBSCRIBE_DEPTH_QUOTES_RES: 2157,
  PROTO_OA_UNSUBSCRIBE_DEPTH_QUOTES_REQ: 2158,
  PROTO_OA_UNSUBSCRIBE_DEPTH_QUOTES_RES: 2159,
  PROTO_OA_SYMBOL_LIST_REQ: 2114,
  PROTO_HEARTBEAT_EVENT: 51
} as const;

export type ProtoOAPayloadTypeId =
  (typeof ProtoOAPayloadType)[keyof typeof ProtoOAPayloadType];

/** ProtoOAOrderType */
export const ProtoOAOrderType = {
  MARKET: 1,
  LIMIT: 2,
  STOP: 3,
  MARKET_RANGE: 4,
  STOP_LIMIT: 5
} as const;

/** ProtoOATradeSide */
export const ProtoOATradeSide = {
  BUY: 1,
  SELL: 2
} as const;

/** ProtoOAExecutionType */
export const ProtoOAExecutionType = {
  ORDER_ACCEPTED: 2,
  ORDER_FILLED: 3,
  ORDER_REPLACED: 4,
  ORDER_CANCELLED: 5,
  ORDER_EXPIRED: 6,
  ORDER_REJECTED: 7,
  ORDER_CANCEL_REJECTED: 8,
  SWAP: 9,
  DEPOSIT_WITHDRAW: 10,
  ORDER_PARTIAL_FILL: 11,
  BONUS_DEPOSIT_WITHDRAW: 12
} as const;

export interface CTraderEnvelope {
  clientMsgId?: string;
  payloadType: number;
  payload?: Record<string, unknown>;
}
